import { jsPDF } from 'jspdf';
import type { AnalysisResult } from '../types/index';

export async function generatePdfReport(
    username: string,
    analyses: AnalysisResult[]
): Promise<Buffer> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('RepoView Report', pageWidth / 2, y, { align: 'center' });
    y += 12;

    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`GitHub: @${username}`, pageWidth / 2, y, { align: 'center' });
    y += 8;
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' });
    y += 15;

    // Separator
    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;

    // Each repository
    for (const analysis of analyses) {
        // Check if we need a new page
        if (y > 250) {
            doc.addPage();
            y = 20;
        }

        // Repo name and score
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(analysis.repoName, 20, y);

        const scoreText = `${analysis.percentage}/100 (${analysis.tier.toUpperCase()})`;
        doc.setFontSize(14);
        doc.text(scoreText, pageWidth - 20, y, { align: 'right' });
        y += 10;

        // Strengths
        if (analysis.strengths.length > 0) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(34, 139, 34); // Green
            doc.text('Strengths:', 20, y);
            y += 6;

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            for (const strength of analysis.strengths.slice(0, 5)) {
                doc.text(`• ${strength}`, 25, y);
                y += 5;
            }
            y += 3;
        }

        // Weaknesses
        if (analysis.weaknesses.length > 0) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(178, 34, 34); // Red
            doc.text('Weaknesses:', 20, y);
            y += 6;

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            for (const weakness of analysis.weaknesses.slice(0, 5)) {
                doc.text(`• ${weakness}`, 25, y);
                y += 5;
            }
            y += 3;
        }

        // Suggestions
        if (analysis.suggestions.length > 0) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(70, 130, 180); // Steel blue
            doc.text('Suggestions:', 20, y);
            y += 6;

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            for (const suggestion of analysis.suggestions.slice(0, 3)) {
                const lines = doc.splitTextToSize(`• ${suggestion}`, pageWidth - 50);
                for (const line of lines) {
                    doc.text(line, 25, y);
                    y += 4;
                }
            }
            y += 3;
        }

        // Reset color
        doc.setTextColor(0);

        // Separator between repos
        doc.setDrawColor(220);
        doc.line(20, y, pageWidth - 20, y);
        y += 10;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text('Generated by RepoView - No AI was used in this analysis', pageWidth / 2, 290, { align: 'center' });

    // Return as buffer
    const arrayBuffer = doc.output('arraybuffer');
    return Buffer.from(arrayBuffer);
}
